PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://purl.org/NET/crm-owl#>
PREFIX claros: <http://purl.org/NET/Claros/vocab#>
PREFIX pf:  <http://jena.hpl.hp.com/ARQ/property#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT { ?s claros:subject-has-type ?t }
WHERE
{ GRAPH ?g
  {
  ?s rdf:type crm:E22.Man-Made_Object ;
    crm:P2.has_type
      [ rdf:type crm:E55.Type ;
        crm:P127.has_broader_term claros:ObjectType ;
        rdf:value ?t 
      ] .
  }
}

